

# Shortcuts
    [shortcuts]
    # Fenster schließen
    super-q = "close"
    # Kompositor beenden
    super-shift-q = "quit"
    # Terminal starten
#    super-t = { type = "exec", exec = "ghostty" }
    # Screenshot mit slurp und grim
    super-p = { type = "exec", exec = ["nu", "-c", "slurp | grim -g \\$in - | wl-copy"] }
    # Screenshot des aktuellen Monitors
    super-shift-p = { type = "exec", exec = ["nu", "-c", "grim -o (jay randr | grep current | awk '{print $2}') - | wl-copy"] }
    # Vollbild umschalten
    super-f = "toggle-fullscreen"
    # Floating-Modus umschalten
    super-shift-f = "toggle-floating"
    # Fokus bewegen
    super-h = "focus-left"
    super-j = "focus-down"
    super-k = "focus-up"
ctrl-q = "quit"
    super-l = "focus-right"
    # Fenster bewegen
    super-shift-h = "move-left"
    super-shift-j = "move-down"
    super-shift-k = "move-up"
    super-shift-l = "move-right"
    # Workspaces wechseln
    super-1 = { type = "show-workspace", name = "1" }
    super-2 = { type = "show-workspace", name = "2" }
    super-3 = { type = "show-workspace", name = "3" }
    super-4 = { type = "show-workspace", name = "4" }
    # Fenster zu Workspaces bewegen
    super-shift-1 = { type = "move-to-workspace", name = "1" }
    super-shift-2 = { type = "move-to-workspace", name = "2" }
    super-shift-3 = { type = "move-to-workspace", name = "3" }
    super-shift-4 = { type = "move-to-workspace", name = "4" }
    # Monitorfokus wechseln
    super-Next = { type = "focus-output", direction = "right" }
    super-Prior = { type = "focus-output", direction = "left" }
    # Workspace zu anderem Monitor bewegen
    super-shift-Next = { type = "move-workspace-to-output", direction = "right" }
    super-shift-Prior = { type = "move-workspace-to-output", direction = "left" }
    super-shift-Home = { type = "move-workspace-to-output", direction = "right" }
    super-shift-End = { type = "move-workspace-to-output", direction = "left" }
    # Anyrun starten
    Super_Space = { type = "exec", exec = ["nu", "-c", "anyrun | jay dispatch -- \\$in"] }
    # Audio-Steuerung
    XF86AudioRaiseVolume = { type = "exec", exec = ["wpctl", "set-volume", "@DEFAULT_AUDIO_SINK@", "5%+"] }
    XF86AudioLowerVolume = { type = "exec", exec = ["wpctl", "set-volume", "@DEFAULT_AUDIO_SINK@", "5%-"] }
    XF86AudioMute = { type = "exec", exec = ["wpctl", "set-mute", "@DEFAULT_AUDIO_SINK@", "toggle"] }
    XF86AudioPlay = { type = "exec", exec = ["playerctl", "play-pause"] }
    XF86AudioPrev = { type = "exec", exec = ["playerctl", "previous"] }
    XF86AudioNext = { type = "exec", exec = ["playerctl", "next"] }


  # Monitore
    [[outputs]]
    name = "HDMI-A-1"
    match.serial-number = "111NTYT0X610"

    x = 0
    y = 0
    scale = 2

   [theme]
    border-width = 2
    gap-width = 8
    outer-gap-width = 16
